site_name: Auto power off
nav:
  - index.md
  - design.md
  - program.md
theme:
  language: ja
  name: material
  palette:
    scheme: slate
  features:
    - navigation.footer
    - content.code.copy
markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format